AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'bin/*'
Metrics/LineLength:
  Max: 100
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
